version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      NODE_ENV: production
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: root
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: teste123
    ports:
      - "3306:3306"
